### What is Numpy?

A numpy array is similar to a list. Its usually fixed in size and each element is of the same type. 

In [1]:
import numpy as np

In [2]:
# Create a numpy array

a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [4]:
# print each element

print("a[0]: ", a[0])
print("a[1]: ", a[1])
print("a[2]: ", a[2])
print("a[3]: ", a[3])
print("a[4]: ", a[4])

a[0]:  0
a[1]:  1
a[2]:  2
a[3]:  3
a[4]:  4


In [5]:
# check the type of an array

type(a)

numpy.ndarray

In [8]:
# check the type of values stored in an array

a.dtype

dtype('int32')

In [15]:
b = np.array([3.1, 10.1, 11.0, 23.4, 45.2])

In [18]:
type(b)
b.dtype

dtype('float64')

In [21]:
# Assign value 

c = np.array([20,1,2,3,4])

In [22]:
c

array([20,  1,  2,  3,  4])

In [23]:
c[0] = 100

In [24]:
c

array([100,   1,   2,   3,   4])

In [25]:
c[4]=0

In [26]:
c

array([100,   1,   2,   3,   0])

#### Slicing

In [28]:
d = c[0:3]
d

array([100,   1,   2])

In [29]:
d = c[2:5]
d

array([2, 3, 0])

### Assign value with list

In [30]:
# Create an index list

select = [0,2,3]

In [31]:
d = c[select]
d

array([100,   2,   3])

In [32]:
c[select] = 10000
c

array([10000,     1, 10000, 10000,     0])

### Other attributes

In [35]:
#get the size of numpy array

a = np.array([0,1,2,3,4])
a.size

5

In [36]:
#get the number of dimensions of numpy array

a.ndim

1

In [37]:
# Get the shape and size of numpy array

a.shape

(5,)

In [38]:
a = np.array([1,-1,1,-1])
a

array([ 1, -1,  1, -1])

In [42]:
mean = a.mean()
mean

0.0

In [44]:
stddev = a.std()
stddev

1.0

In [45]:
b = np.array([-1,2,3,4,5])
b

array([-1,  2,  3,  4,  5])

In [47]:
max_b = b.max()
max_b

5

In [49]:
min_b = b.min()
min_b

-1

### Numpy Array Operations

#### Array Addition

In [51]:
u = np.array([1,0])
u

array([1, 0])

In [53]:
v = np.array([0,1])
v

array([0, 1])

In [55]:
z = u + v
z

array([1, 1])

#### Array Multiplication

In [57]:
y = np.array([9,3])
y

array([9, 3])

In [59]:
x = 2 * y
x

array([18,  6])

#### Product of two numpy arrays

In [61]:
u = np.array([2,3])
v = np.array([5,2])

In [63]:
z = u * v
z

array([10,  6])

#### Dot Product

In [64]:
np.dot(u,v)

16

In [68]:
#### Adding constant to an array

u = np.array([-1,2,3,4])

z = u + 1

In [69]:
z

array([0, 3, 4, 5])

#### Mathematical functions

In [70]:
# The value of pi

np.pi

3.141592653589793

In [73]:
a = np.array([1.0, np.pi/2, np.pi/4])
a

array([1.        , 1.57079633, 0.78539816])

In [75]:
b = np.sin(a)
b

array([0.84147098, 1.        , 0.70710678])