### Create a 2D numpy array

In [1]:
import numpy as np

In [4]:
# Create a list

a = [[1,2,3], [11,12,13], [21,22,23]]
a

[[1, 2, 3], [11, 12, 13], [21, 22, 23]]

In [8]:
A = np.array(a)
A

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [9]:
# Show the numpy array dimensions

A.ndim

2

In [10]:
# Show the numpy array size

A.size

9

In [11]:
A.shape

(3, 3)

### Accessing different elements of numpy array

In [16]:
print("1st row, 1st element: ", A[0,0])
print("1st row, 2nd element: ", A[0,1])
print("1st row, 3rd element: ", A[0,2])
print("2nd row, 1st element: ", A[1,0])
print("2nd row, 2nd element: ", A[1,1])
print("2nd row, 3rd element: ", A[1,2])
print("3rd row, 1st element: ", A[2,0])
print("3rd row, 2nd element: ", A[2,1])
print("3rd row, 3rd element: ", A[2,2])

1st row, 1st element:  1
1st row, 2nd element:  2
1st row, 3rd element:  3
2nd row, 1st element:  11
2nd row, 2nd element:  12
2nd row, 3rd element:  13
3rd row, 1st element:  21
3rd row, 2nd element:  22
3rd row, 3rd element:  23


In [25]:
# Access the element on the first row and first and second columns

print(A[0,0:2])
print(A[0][0:2])

[1 2]
[1 2]


### Basic Operations

In [27]:
x = np.array([[1,2],[2,1]])
x

array([[1, 2],
       [2, 1]])

In [28]:
y = np.array([[3,4],[2,3]])
y

array([[3, 4],
       [2, 3]])

In [29]:
z = x + y
z

array([[4, 6],
       [4, 4]])

In [31]:
z = 2 * x
z

array([[2, 4],
       [4, 2]])

In [33]:
z = x * y
z

array([[3, 8],
       [4, 3]])

#### Dot product (Matrix multiplication)

In [34]:
x = np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [35]:
y = np.array([[1,2],[3,4],[5,6]])
y.shape

(3, 2)

In [37]:
z = np.dot(x,y)
z

array([[22, 28],
       [49, 64]])

In [39]:
zz = np.sin(z)
zz

array([[-0.00885131,  0.27090579],
       [-0.95375265,  0.92002604]])

#### Transpose a Matrix

In [40]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])